### ISSUE TITLE
UCnn.x TitleOfRecipe

### ISSUE THREAD

**Issue by robertgiessmann** [FAIRplus/the-fair-cookbook#102]
The following checklists will guide you through the process of advancing a recipe through its pipeline. You can click on "Submit new Issue" now, and read on later.

For issue meta-management, please conduct the following steps:

- [x] change the title of this issue with the corresponding Use Case Number (at the top: click "Edit" -> change "UCnn.x TitleOfRecipe" correspondingly -> click "Save")
- [x] assign this issue to yourself or whoever is responsible to advance this recipe through the next steps; usually this is the facilitator, i.e. Squad lead (at your right side: click "Assignees" -> "...")
- [x] label this issue with the corresponding Use Case Number (at your right side: click "Labels" -> "UC..."
- [ ] add this issue to the corresponding Project, i.e. Kanban board (at your right side: click "Projects" -> "UC..."

Great! Now, to the actual tasks:

- [ ] facilitator: identify author for this recipe
- [ ] facilitator: agree with editors on scope and position within the cookbook 
- [ ] author: write abstract; share via issue (LINK TO ISSUE HERE) 
- [ ] editors: write feedback on abstract; share via issue  (LINK TO ISSUE HERE)
- [ ] author: make corresponding changes to abstract
- [ ] author: write recipe; share the recipe  (LINK TO ISSUE HERE)
- [ ] facilitator: identify reviewer for this recipe 
- [ ] reviewer: conduct review; share the review output  (LINK TO ISSUE HERE)
- [ ] author: introduce reviewer's comments
- [ ] editors: incorporate recipe into cookbook (LINK TO ISSUE HERE)

Cool, that's it! 

If you needed to add a task to the list above, please think about amending the issue template: https://github.com/FAIRplus/the-fair-cookbook/blob/master/.github/ISSUE_TEMPLATE/meta-checklist.md

**Comment by robertgiessmann** [comment]
dummy, can be deleted
