### ISSUE TITLE
UCnn.x How to use Zooma to identify new ontology annotations

### ISSUE THREAD

**Issue by JolandaS** [FAIRplus/the-fair-cookbook#132]
The following checklists will guide you through the process of advancing a recipe through its pipeline. You can click on "Submit new Issue" now, and read on later.

For issue meta-management, please conduct the following steps:

- [x] label this issue with the corresponding Use Case Number (at your right side: click "Labels" -> "UC..."

- [x] change title to final title
- [x] identify author - Fuqi
- [ ] agree with editors on scope
- [ ] write abstract
- [ ] write feedback on abstract
- [x] make corresponding changes to abstract
- [x] write recipe
- [ ] identify reviewer
- [ ] conduct review
- [ ] incorporate reviewer's comments
- [ ] publish recipe

**Comment by FuqiX** [comment]
The zooma first draft is [here](https://github.com/FAIRplus/the-fair-cookbook/blob/zooma-automatic-ontology-annotation/docs/content/recipes/interoperability/ontology-annotation-zooma.md) I'll finalize the contents this week,
