### ISSUE TITLE
UCnn.x Public metadata in DATS format and how to import into the IMI data catalogue

### ISSUE THREAD

**Issue by JolandaS** [FAIRplus/the-fair-cookbook#133]
- [ ] change to final title
- [ ] label this issue with the corresponding Use Case Number (at your right side: click "Labels" -> "UC..."

- [x] identify author - Danielle, Philippe
- [ ] agree with editors on scope
- [ ] write abstract
- [ ] write feedback on abstract
- [ ] make corresponding changes to abstract
- [ ] write recipe
- [ ] identify reviewer
- [ ] conduct review
- [ ] incorporate reviewer's comments
- [ ] publish recipe

**Comment by JolandaS** [comment]
@daniwelter What are feasible timelines for this recipe regarding writing? I would like to identify the reviewer at this point. Any suggestions on who that could be?

**Comment by daniwelter** [comment]
@JolandaS This is the one of my recipes I haven't even started on yet as I'm in the middle of doing the actual work in the data catalogue. I'll touch base with @proccaserra to see if we can put something together on time for the f2f but we may need to push this recipe to the next release cycle.
