### ISSUE TITLE
UCnn.x How to map internal ontologies to existing, public ontologies using OXO

### ISSUE THREAD

**Issue by JolandaS** [FAIRplus/the-fair-cookbook#135]
- [ ] change the title of this issue with the corresponding Use Case Number 
- [ ] Change title to final title 
- [ x ] identify author
- [ ] agree with editors on scope
- [ ] write abstract
- [ ] write feedback on abstract
- [ ] make corresponding changes to abstract
- [ ] write recipe
- [ ] identify reviewer
- [ ] conduct review
- [ ] incorporate reviewer's comments
- [ ] publish recipe

**Comment by JolandaS** [comment]
Is this issue related to #126?

**Comment by FuqiX** [comment]
@jolanda yes. And it will be better to have a separate issue for the oxo one.Thanks for linking the issues.On 14 Oct 2020 14:19, Jolanda Strubel <notifications@github.com> wrote:
Is this issue related to #126?

**Comment by JolandaS** [comment]
@FuqiX What is feasible for this recipe to have done before the next F2F? Who would be a logical reviewer? (I will also ask this in the squad call today)

**Comment by FuqiX** [comment]
I have completed the first draft [here](https://github.com/FAIRplus/the-fair-cookbook/blob/ontology_mapping_oxo/docs/content/recipes/interoperability/ontology-mapping-oxo.md) I'll contact internal reviewers this week. And hopefully have a internal reviewed version next week.

**Comment by Chris-Evelo** [comment]
Thanks @FuqiX. I still have to read it, but I actually had the impression that OxO cannot map from something that it doesn't have loaded and that OLS itself should be used to find something based on labels, since that is actually a lookup and not a mapping across ontologies? I am curious how that will work then.

**Comment by JolandaS** [comment]
@Chris-Evelo Are you the official reviewer for this recipe? Or will Lucas (@mavrokefalidis) take this as well?
