### ISSUE TITLE
Apply for EGA genomic data

### ISSUE THREAD

**Issue by nsjuty** [FAIRplus/the-fair-cookbook#136]
The following checklists will guide you through the process of advancing a recipe through its pipeline. You can click on "Submit new Issue" now, and read on later.

For issue meta-management, please conduct the following steps:

- [ ] change the title of this issue with the corresponding Use Case Number (at the top: click "Edit" -> change "UCnn.x TitleOfRecipe" correspondingly -> click "Save")
- [ ] assign this issue to yourself or whoever is responsible to advance this recipe through the next steps; usually this is the facilitator, i.e. Squad lead (at your right side: click "Assignees" -> "...")
- [ ] label this issue with the corresponding Use Case Number (at your right side: click "Labels" -> "UC..."
- [ ] add this issue to the corresponding Project, i.e. Kanban board (at your right side: click "Projects" -> "UC..."

Now you can delete the text above.
If you needed to add a task to the list below, please think about amending the issue template: https://github.com/FAIRplus/the-fair-cookbook/blob/master/.github/ISSUE_TEMPLATE/meta-checklist.md
Great! Now, to the actual tasks:

- [ ] identify author
- [ ] agree with editors on scope
- [ ] write abstract
- [ ] write feedback on abstract
- [ ] make corresponding changes to abstract
- [ ] write recipe
- [ ] identify reviewer
- [ ] conduct review
- [ ] incorporate reviewer's comments
- [ ] publish recipe

**Comment by nsjuty** [comment]
set up

**Comment by nsjuty** [comment]
uc added
