### ISSUE TITLE
UCnn.x Anonymizing Patient Data

### ISSUE THREAD

**Issue by JolandaS** [FAIRplus/the-fair-cookbook#142]
- [ ] label this issue with the corresponding Use Case Number (at your right side: click "Labels" -> "UC..."
- [x] identify author (Melanie? Kurt, David)
- [ ] agree with editors on scope
- [ ] write abstract
- [ ] write feedback on abstract
- [ ] make corresponding changes to abstract
- [ ] write recipe
- [ ] identify reviewer
- [ ] conduct review
- [ ] incorporate reviewer's comments
- [ ] publish recipe

**Comment by JolandaS** [comment]
Recipe stub already in place (see [here](https://github.com/FAIRplus/the-fair-cookbook/blob/dev/docs/content/recipes/accessibility/anonymization.md)

**Comment by mcourtot** [comment]
I have very limited experience with anonymising patient data - BioSamples is an open archive and we only accept open metadata.

**Comment by JolandaS** [comment]
@kurtdauth you indicated that someone from within BI (not connected to FAIRplus) would be willing to write a recipe on this. As this is a substantial recipe, could you ask that person what he/she is able to deliver before the next F2F? (16-18th of November)

**Comment by JolandaS** [comment]
On hold until January

**Comment by proccaserra** [comment]
Review the following tool  AMNESIA:
- [ ] https://amnesia.openaire.eu/about-documentation.html
- [ ] https://amnesia.openaire.eu/download.html#

@weiguUL @satagopam7 @daniwelter @kurtdauth any experience with it?
