### ISSUE TITLE
UCnn.x EHDEN and OHDSI FAIRification recipe

### ISSUE THREAD

**Issue by JolandaS** [FAIRplus/the-fair-cookbook#148]
- [ ] change the title of this issue with the corresponding Use Case Number 
- [x] identify author
- [ ] agree with editors on scope
- [ ] write abstract
- [ ] write feedback on abstract
- [ ] make corresponding changes to abstract
- [ ] write recipe
- [ ] identify reviewer
- [ ] conduct review
- [ ] incorporate reviewer's comments
- [ ] publish recipe
