### ISSUE TITLE
FCB007: update chemical-identities to current template

### ISSUE THREAD

**Issue by egonw** [FAIRplus/the-fair-cookbook#313]
About: https://fairplus.github.io/the-fair-cookbook/content/recipes/infrastructure/chemical-identities.html

- [x] identify author
- [x] agree with editors on scope
- [x] write abstract
- [x] write feedback on abstract
- [x] make corresponding changes to abstract
- [x] write recipe
- [x] identify reviewer
- [ ] conduct review
- [ ] incorporate reviewer's comments
- [ ] publish recipe

**Comment by lucas-ubm** [comment]
Hi Egon, find here https://github.com/FAIRplus/the-fair-cookbook/blob/dev/docs/content/recipes/help/recipe-template.md the recipe template currently being used.

**Comment by egonw** [comment]
Started working on this: https://github.com/FAIRplus/the-fair-cookbook/pull/314

**Comment by proccaserra** [comment]
@egonw @lucas-ubm. the template is a bit outdated. about to push changes

**Comment by proccaserra** [comment]
here is the updating link:
https://github.com/FAIRplus/the-fair-cookbook/blob/migrating/content/recipes/help/recipe-template.md

**Comment by egonw** [comment]
@lucas-ubm, can you have a look at the changes and see if you see something obvious that I still have to do?

**Comment by robertgiessmann** [comment]
Looks good to me in general. In https://github.com/FAIRplus/the-fair-cookbook/pull/314/files#diff-be79f97d387022d3ff21daae7f5a317a9ba2d2ea1fb1468f52aa63f2adfa3efb there are changes to the .github directory, that shouldn't be in there, I believe.

**Comment by egonw** [comment]
Correct, the branch has some patches to get the deployment working... sorry, was trying to get branches to deply correctly, and forgot to remove them. The first patch is 3514c14

**Comment by egonw** [comment]
@robertgiessmann, I fixed the PR now to what it was supposed to be: https://github.com/FAIRplus/the-fair-cookbook/pull/314/files

**Comment by robertgiessmann** [comment]
Looks great to me!
