### ISSUE TITLE
Develop a candidate recipe documenting FAIR-checker tool

### ISSUE THREAD

**Issue by albangaignard** [FAIRplus/the-fair-cookbook#341]
FAIR-checker is a web tool leveraging FAIR Evaluator APIs and proposing additional validations to enhance the metadata quality of Life Science digital resources. 

We would like to propose an overview of the main features of FAIR-checker based on one or two concrete examples. We could also showcase semantic web technologies used in the backend through an interactive jupyter notebook dedicated to developers. 

- [X] identify author
- [ ] agree with editors on scope
- [ ] write abstract
- [ ] write feedback on abstract
- [ ] make corresponding changes to abstract
- [ ] write recipe
- [ ] identify reviewer
- [ ] conduct review
- [ ] incorporate reviewer's comments
- [ ] publish recipe

**Comment by albangaignard** [comment]
@mddevignes and @thomasrosnet will also contribute to the recipe.

**Comment by albangaignard** [comment]
@proccaserra, we started a draft for a FAIR-Checker recipe. Here is a tentative abstract : 

> FAIR-Checker is a web tool to mine and analyze machine readable metadata found in web pages. In this recipe, you will learn how to use FAIR-Checker to i) evaluate FAIR maturity indicators for your web resource, ii) inspect the metadata content of your resource. Finally, in iii) you will go through an executable Jupyter notebook intended to demonstrate how RDF metadata can be extracted and queried. This may allow you to extend computational assessments for your specific community needs. 

We forked the repository and created a specific branch here : https://github.com/IFB-ElixirFr/the-fair-cookbook/tree/fair-checker 

Thanks in advance for your feedback.

**Comment by albangaignard** [comment]
When launching inside the root directory `jupyter-book build -W -n --keep-going .`, we face the following error : 
``` 
  File "/Users/gaignard-a/Documents/Dev/the-fair-cookbook/_ext/panels_fairplus.py", line 34, in _clean_options
    assert option_name in self.options, \
AssertionError: You did not provide the required option maturity_level.
```

@proccaserra, are we missing something in the build process ?
