### ISSUE TITLE
MIAPPE and plant data submission recipe

### ISSUE THREAD

**Issue by FuqiX** [FAIRplus/the-fair-cookbook#343]
A recipe about the MIAPPE data standard and how to submit data to BioSD, EVA and ENA.

More information in the FONDUE datathon page. https://github.com/PBR/elixir-fondue-datathon

branch and doc here: https://github.com/FAIRplus/the-fair-cookbook/blob/MIAPPE/content/recipes/reusability/miappe.md

cc @sebeier 

- [x] identify author (TBD mid July）
- [x] agree with editors on scope
- [ ] write abstract
- [ ] write feedback on abstract
- [x] make corresponding changes to abstract
- [x] write recipe
- [ ] identify reviewer
- [ ] conduct review
- [ ] incorporate reviewer's comments
- [ ] publish recipe

**Comment by FuqiX** [comment]
the MIAPPE meeting was postponed to late August. Further updates will be provided after that meeting.

**Comment by FuqiX** [comment]
The MIAPPE recipe draft is[ here (WIP)](https://docs.google.com/document/d/1mwmXAOyaIo64Trqfm9t3WnEzMpOp9JZXLIiMi7uENWA/edit?usp=sharing)
@sebeier is writing up focusing on MIAPPE genotyping and linked submission.

There are also two recipes related in the RDMkit

**Comment by FuqiX** [comment]
recipe updated in this recipe. https://hackmd.io/HpEj4KexTdu353ri3rBjAQ?both

**Comment by ErwanLeFloch** [comment]
Hi @FuqiX , here is my handle. Looking forward to the recipe :)

**Comment by FuqiX** [comment]
@ErwanLeFloch  do you mind having a look at the doc, so that we can pass it to the cookbook editorial board? Thanks!

**Comment by ErwanLeFloch** [comment]
Hi @FuqiX,
@sebeier and I just finished updating the recipe on the HackMD, it now looks ready for publication.

**Comment by proccaserra** [comment]
https://w3id.org/faircookbook/FCB061
