### ISSUE TITLE
New recipe: application of CDISC-SDTM to semi-structured clinical trials data dictionaries

### ISSUE THREAD

**Issue by daniwelter** [FAIRplus/the-fair-cookbook#374]
Write up the experience of mapping the data dictionaries for APPROACH and ABIRISK to CDISC. Focus on challenges and ETL required to migrate from collected data to full CDISC-compliant data.

- [x] identify author --> Danielle Welter
- [x] write abstract
- [ ] agree with editors on abstract
- [x] write recipe
- [ ] identify reviewer
- [ ] conduct review
- [ ] incorporate reviewer's comments
- [ ] publish recipe

**Comment by robertgiessmann** [comment]
removed my assignment because I cannot help here anymore
