### ISSUE TITLE
Port recipe from BioHackathon Europe 2021 about SwissLipids identifiers into Wikidata

### ISSUE THREAD

**Issue by egonw** [FAIRplus/the-fair-cookbook#383]
The following checklists will guide you through the process of advancing a recipe through its pipeline. You can click on "Submit new issue" now, and read on later.

For issue meta-management, please conduct the following steps:

- [x] change the title of this issue to a title that gives sufficient detail about the recipe you want to bring into the cookbook
- [ ] assign this issue also to yourself (at your right side: click "Assignees" -> search for your username here on Github -> click it)

Now you can delete the text above.
If you needed to add a task to the list below, please think about amending the issue template: https://github.com/FAIRplus/the-fair-cookbook/blob/migrating/.github/ISSUE_TEMPLATE/meta-checklist.md
Great! Now, to the actual tasks:

- [x] identify author
- [x] write abstract
- [ ] agree with editors on abstract
- [x] write recipe
- [x] identify reviewer
- [x] conduct review
- [x] incorporate reviewer's comments
- [ ] publish recipe

**Comment by egonw** [comment]
First draft: https://egonw.github.io/cookbook-dev/content/recipes/interoperability/registering-swisslipids-identifiers.html

**Comment by egonw** [comment]
@proccaserra, can you have a look at it and suggest the next step?

**Comment by egonw** [comment]
https://github.com/FAIRplus/the-fair-cookbook/pull/424 has been merged in.
