### ISSUE TITLE
UC27.3 Sharing data using Aspera

### ISSUE THREAD

**Issue by JolandaS** [FAIRplus/the-fair-cookbook#80]
Sharing mechanism using Aspera

- [x] get Peter on board of this repo
- [x] assign recipe writer: Peter
- [x] draft recipe : Peter
- [x] write recipe in template : Peter
- [x] convert recipe to Markdown @robertgiessmann 
- [x] add in the text description from the google docs version to Markdown - Peter
- [x] assign reviewer (Philippe @proccaserra) 
- [ ] review
- [ ] publish

**Comment by JolandaS** [comment]
Peter not in Repo yet, Need to assign Reviewer

**Comment by PeterWoollard** [comment]
Drafted this in OneNote now to paste to Google Drive

**Comment by PeterWoollard** [comment]
Recipe now drafted in the googledocs and includes a Mermid flow diagram  https://docs.google.com/document/d/1EcarVg26W0U1M3NXYAUMXb7lE__nrWBcfETxthTGiZo/edit?usp=sharing

**Comment by robertgiessmann** [comment]
recipe now in markdown:

https://github.com/FAIRplus/the-fair-cookbook/blob/aspera/docs/content/recipes/accessibility/how-to-download-with-aspera.md

**Comment by PeterWoollard** [comment]
Thanks @robertgiessmann for doing that, that has helped.
I pasted in the rest of the material from the google docs, and did a few iterations formatting it.

**Comment by proccaserra** [comment]
http://w3id.org/faircookbook/FCB015
