### ISSUE TITLE
UC27.4 Sharing data using SFTP

### ISSUE THREAD

**Issue by JolandaS** [FAIRplus/the-fair-cookbook#81]
describe SFTP method, currently in use at Novartis)

- [x] assign recipe writer: @dorothyreilly , Ulrich, Vitaly
- [x] write recipe
- [ ] assign reviewer (internal Novartis; UL?)
- [ ] review recipe 
- [x] convert to Markdown, put in specific branch @robertgiessmann 
- [ ] publish

link to recipe: 
https://github.com/FAIRplus/the-fair-cookbook/blob/sftp/docs/content/recipes/accessibility/how-to-use-sftp-for-transfer.md

**Comment by JolandaS** [comment]
assign reviewer

**Comment by robertgiessmann** [comment]
> assign reviewer

--> made this a checklist item

**Comment by robertgiessmann** [comment]
again, I would find an abstract helpful

**Comment by dorothyreilly** [comment]
Hello All, 
I wrote a **very** rough draft (using the format of the google doc template) and sent it to Vitaly Sedlyarov and Ulrich Goldmann (CEMM, ReSOLUTE), who kindly agreed to work on this with me. I included some links to published protocols, since this is not a "novel" process.
Dorothy

(partial info below, not full draft)
How to use SFTP to transfer data files between collaborating institutions.

**Abstract:**
FAIRplus UC27 FAIR Cookbook recipe: SFTP data transfer between collaborating institutions.

Collaborating teams at two or more organizations often need to transfer and share data files. There are a number of ways to share files, all with various degrees of ease and usability. 
The particular information security risk management (ISRM) protocols at the sending and receiving institutions need to be considered when one chooses and optimizes file-transfer solutions.
One common method for transferring files is SFTP or scp (secure copy): 
SFTP: Secure or SSH File Transfer protocol is a standard way to transfer files securely using a remote server. 

**links:**
- Wikipedia article on SFTP: https://en.wikipedia.org/wiki/SSH_File_Transfer_Protocol
- The Geek Stuff, FTP and SFTP Beginners guide with 10 examples https://www.thegeekstuff.com/2010/06/ftp-sftp-tutorial/
- Example of customization for a specific institution, https://hpc.uni.lu/users/docs/filetransfer.html
-

**Comment by dorothyreilly** [comment]
Hello all, 
I wrote a terrible recipe, I sent it to Vitaly Sedlyarov and Ulrich Goldmann, and they fixed it. So it is much better now! (please see attached file)
Which is great because I have never used SFTP, and now I can confirm that the recipe needs to be written by some one who has done the process (not a surprise). 
Let's discuss at squads, I would like to ask for some help putting this in the proper markdown format, and then I propose to ask Vitaly if he and Ulrich would kindly check this recipe in markdown, before we ask for an "outside" reviewer. 
Thank you, Dorothy
[20200706_UC27_SFTP_recipe_v3dsr.docx](https://github.com/FAIRplus/the-fair-cookbook/files/4885028/20200706_UC27_SFTP_recipe_v3dsr.docx)

**Comment by robertgiessmann** [comment]
Great, thank you @dorothyreilly ! Having volunteered for Markdown conversion, this will be my task.

**Comment by robertgiessmann** [comment]
@dorothyreilly @sedlyarov here is the first dump of the recipe: https://github.com/FAIRplus/the-fair-cookbook/blob/0713012dc252d0169aacd67d40e752a42c9cc4a1/docs/content/recipes/accessibility/how-to-use-sftp-for-transfer.md

**Comment by proccaserra** [comment]
https://w3id.org/faircookbook/FCB014
