### ISSUE TITLE
UC30.2 FASTQ validator (step-by-step recipe)

### ISSUE THREAD

**Issue by robertgiessmann** [FAIRplus/the-fair-cookbook#95]
- [x] write abstract
- [x] write recipe #75 
- [x] send out to interested reviewers
- [ ] review (Peter) @PeterWoollard https://docs.google.com/forms/d/e/1FAIpQLSeY3kf1TTNrnDbR1yLe96LQC3_GhIn1LGpwFFtpt4EDNebD6w/viewform
- [ ] incorporate review comments

**Comment by robertgiessmann** [comment]
@PeterWoollard , did you have the chance to review this recipe? Feedback deeply appreciated. :)

**Comment by robertgiessmann** [comment]
@PeterWoollard, I found your review, thanks! https://docs.google.com/forms/d/1jMYeKCCQ8scquyNE9Cbgv2_BbavB405z1YDAu9bjwAE/edit#response=ACYDBNizh614KohaDT_tHgXqH6-VvTpvWlVhyJwlOLw3GkPqCIcvDyqifFzyWDQH0_AM0HY
