### ISSUE TITLE
UC27.1 + UC27.2 Checksum creation and validation (step-by-step recipes)

### ISSUE THREAD

**Issue by robertgiessmann** [FAIRplus/the-fair-cookbook#96]
- [x] write recipe UC27.1 #77 
- [x] write recipe UC27.2 #77 
- [x] assign reviewer
- [ ] review UC27.1 @PeterWoollard https://docs.google.com/forms/d/e/1FAIpQLSeY3kf1TTNrnDbR1yLe96LQC3_GhIn1LGpwFFtpt4EDNebD6w/viewform
- [ ] review UC27.2 @PeterWoollard https://docs.google.com/forms/d/e/1FAIpQLSeY3kf1TTNrnDbR1yLe96LQC3_GhIn1LGpwFFtpt4EDNebD6w/viewform
- [ ] incorporate review comments UC27.1
- [ ] incorporate review comments UC27.2

**Comment by robertgiessmann** [comment]
@PeterWoollard , same here. did you have the chance to review this recipe?

**Comment by robertgiessmann** [comment]
@PeterWoollard , sorry, I got you wrong here, the actual reviewer is KurtDauth.

**Comment by robertgiessmann** [comment]
this is a duplicate of #78 ; will close
